name: E2E test

on:
  push:
    branches-ignore:
    - "dependabot/*"

jobs:
  e2e:
    runs-on: ubuntu-16.04
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    # just so we learn about available environment variables Zeit Now provides
    - uses: hmarr/debug-action@master
    - name: Cache Next.js build
      uses: actions/cache@v2
      with:
        path: .next/cache
        key: ${{ runner.os }}-next-build-${{ hashFiles('**/next.config.js') }}
    - name: Cypress run
      uses: cypress-io/github-action@v2
      timeout-minutes: 10
      env:
        CODE_COVERAGE: true
        APP_SECRET: c67d158338b7e5df7ff128228c74de33cb7a23f388d1c57c6b0df8fb1c825fad58d33a1eba4ffb6fcfc638a2470abff1583707a6c9ae076575a0f0639eb1b08e
      with:
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:3000'
        browser: ${{ matrix.browser }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Cypress screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Cypress video
        path: cypress/videos
    - run: npx nyc report
    - uses: actions/upload-artifact@v2
      with:
        name: e2e-coverage
        path: coverage/e2e
