name: Unit test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint_flags: --ext '.js' --ext '.ts' --ext '.tsx' .

  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - uses: icrawl/action-tsc@v1

  unit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - uses: actions/cache@v1
      name: Cache Next.js build
      with:
        path: .next/cache
        key: ${{ runner.os }}-next-build
        restore-keys: |
          ${{ runner.os }}-next-build-
    - name: npm test
      run: |
        npm test -- --coverage
      env:
        CI: true
        APP_SECRET: c67d158338b7e5df7ff128228c74de33cb7a23f388d1c57c6b0df8fb1c825fad58d33a1eba4ffb6fcfc638a2470abff1583707a6c9ae076575a0f0639eb1b08e
    - uses: actions/upload-artifact@v1
      with:
        name: unit-coverage
        path: coverage/unit
