name: Unit test

on: [push]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - uses: actions/cache@v1
      name: Cache Next.js build
      with:
        path: .next/cache
        key: ${{ runner.os }}-next-build
        restore-keys: |
          ${{ runner.os }}-next-build-
    - name: npm install, build, and test
      run: |
        npm run build --if-present
        npm test -- --coverage
      env:
        CI: true
        APP_SECRET: c67d158338b7e5df7ff128228c74de33cb7a23f388d1c57c6b0df8fb1c825fad58d33a1eba4ffb6fcfc638a2470abff1583707a6c9ae076575a0f0639eb1b08e
    - uses: actions/upload-artifact@v1
      with:
        name: unit-coverage
        path: coverage/unit
