name: Unit test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hallee/eslint-action@1.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - uses: icrawl/action-tsc@v1

  unit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - uses: actions/cache@v2
      name: Cache Next.js build
      with:
        path: .next/cache
        key: ${{ runner.os }}-next-build-${{ hashFiles('**/next.config.js') }}
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        JWT_ISSUER: unit-tests
      with:
        coverageCommand: npm test -- --coverage
        coverageLocations: |
          ${{ github.workspace }}/coverage/unit/lcov.info:lcov
    - name: Monitor coverage
      if: "github.event_name == 'pull_request'"
      uses: slavcodev/coverage-monitor-action@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clover_file: coverage/unit/clover.xml
        threshold_alert: 50
        threshold_warning: 80
    - uses: actions/upload-artifact@v2
      with:
        name: unit-coverage
        path: coverage/unit
